config/routes.rb
Rails.application.routes.draw do

  scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do

    resources :accounting_records

    resources :categories
    resources :customers do 
      get 'find/:id' => 'customers#find', as: :store, :on =>  :collection
      resources :current_accounts
    end

    resources :invoice_stocks
    resources :stocks
    resources :brands
    resources :orders do
    end
    resources :invoices do
      get :autocomplete_customer_name, :on => :collection
    end
    resources :suppliers
    resources :articles

    devise_for :users
    resources :users

  end 

  authenticated :user do 
    root :to => 'articles#index'
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

end

app/models/current_account.rb
class CurrentAccount < ActiveRecord::Base

  belongs_to :customer
  
#  after_create :create_accounting_record



  def self.total(current_account)
    credit = 0
    debit = 0
    @current_account = current_account
    @current_account.each { |a| 
      credit += a.credit.to_f
      debit += a.debit.to_f
    } 
        @result = {credit: credit, debit: debit}
  end


  def create_accounting_record
      @record = AccountingRecord.create(detail: detail , debit: debit)
  end


end

app/controllers/current_accounts_controller.rb
class CurrentAccountsController < ApplicationController
  before_action :set_current_account, only: [:show, :edit, :update, :destroy]
  before_action :customer
  # GET /current_accounts
  # GET /current_accounts.json
  def index
    @current_accounts = CurrentAccount.all

  
  end

  # GET /current_accounts/1
  # GET /current_accounts/1.json
  def show
  end

  # GET /current_accounts/new
  def new
    @current_account = @customer.current_accounts.new
  end

  # GET /current_accounts/1/edit
  def edit
  end

  # POST /current_accounts
  # POST /current_accounts.json
  def create
    @current_account = @customer.current_accounts.new(current_account_params)

    respond_to do |format|
      if @current_account.save
        format.html { redirect_to store_customers_path(@customer), notice: 'Current account was successfully created.' }
        format.json { render :show, status: :created, location: @current_account }
      else
        format.html { render :new }
        format.json { render json: @current_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /current_accounts/1
  # PATCH/PUT /current_accounts/1.json
  def update
    respond_to do |format|
      if @current_account.update(current_account_params)
        format.html { redirect_to @current_account, notice: 'Current account was successfully updated.' }
        format.json { render :show, status: :ok, location: @current_account }
      else
        format.html { render :edit }
        format.json { render json: @current_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /current_accounts/1
  # DELETE /current_accounts/1.json
  def destroy
    @current_account.destroy
    respond_to do |format|
      format.html { redirect_to current_accounts_url, notice: 'Current account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
  def customer

    @customer = Customer.find(params[:customer_id])
  end
  
  # Use callbacks to share common setup or constraints between actions.
    def set_current_account
      @current_account = CurrentAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def current_account_params
      params.require(:current_account).permit(:customer_id, :detail, :debit, :credit)
    end
end

app/helpers/current_accounts_helper.rb
module CurrentAccountsHelper
end

app/views/current_accounts/_form.html.erb
<%= simple_form_for [@customer, @current_account] do |f| %>


  <div class="field">
    <%= f.input :customer_id, label: false, as: :hidden %>
  </div>
  
  <table class="table">
    <tr>
      <td>Detalle</td>
      <td>Pago</td>
    </tr>
    <tr>
      <td><%= f.input :detail, input_html: {class: "form-control"}, label: false %></td>
      <td><%= f.input :debit, input_html: {class: "form-control"}, as: :string, label: false%></td>
    </tr>
  </table>




  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/current_accounts/edit.html.erb
<h1>Editing current_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @current_account %> |
<%= link_to 'Back', current_accounts_path %>

app/views/current_accounts/index.html.erb
<h1>Listing current_accounts</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Detail</th>
      <th>Debit</th>
      <th>Credit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @current_accounts.each do |current_account| %>
      <tr>
        <td><%= current_account.customer_id %></td>
        <td><%= current_account.detail %></td>
        <td><%= current_account.debit %></td>
        <td><%= current_account.credit %></td>
        <td><%= link_to 'Show', current_account %></td>
        <td><%= link_to 'Edit', edit_current_account_path(current_account) %></td>
        <td><%= link_to 'Destroy', current_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Current account', new_current_account_path %>

app/views/current_accounts/new.html.erb
<div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Menu de Navegacion</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
    </div>

    <div class="col-sm-offset-2 col-md-9 col-md-offset-3">
      <h1>Nuevo Pago</h1>

<%= render 'form' %>

</div>
</div>
</div>

app/views/current_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @current_account.customer_id %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @current_account.detail %>
</p>

<p>
  <strong>Debit:</strong>
  <%= @current_account.debit %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @current_account.credit %>
</p>

<%= link_to 'Edit', edit_current_account_path(@current_account) %> |
<%= link_to 'Back', current_accounts_path %>