config/routes.rb
Rails.application.routes.draw do

  scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do

    resources :accounting_records

    resources :categories
    resources :customers do 
      get 'find/:id' => 'customers#find', as: :store, :on =>  :collection
      resources :current_accounts
    end

    resources :invoice_stocks
    resources :stocks
    resources :brands
    resources :orders do
    end
    resources :invoices do
      get :autocomplete_customer_name, :on => :collection
    end
    resources :suppliers
    resources :articles

    devise_for :users
    resources :users

  end 

  authenticated :user do 
    root :to => 'articles#index'
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

end

app/models/accounting_record.rb
class AccountingRecord < ActiveRecord::Base

  scope :by_created_at, lambda {|from, to| where("created_at::date >= ? and created_at::date <= ? ", from, to).order("created_at desc")}

  def self.journal
    @accounting_record = AccountingRecord.where("created_at::date = ?", Date.today).order(created_at: :desc) 

  end

  def self.filters(filters)  
    q = AccountingRecord.all  
    q = by_created_at((filters[:from].to_date), (filters[:to].to_date)) if filters[:from].present? or filters[:to].present?
    q
  end

  def self.credit(invoice)
    sum = 0
    @invoices = invoice
    @invoices.each { |a| sum += a.credit.to_f} 
    sum
  end

  def self.debit(invoice)
    sum = 0
    @invoices = invoice
    @invoices.each { |a| sum += a.debit.to_f} 
    sum
  end
  def self.total
    @invoices = AccountingRecord.where("created_at::date = ?", Date.today).sum(:debit)
  end

  def self.earnings(date=nil)
    sum = 0 
  
    
    @from = Date.today 
    @to = Date.today 
    @from = date[:from] if !date.nil?
    @to = date[:to] if !date.nil?

    @earnings = Article.joins(:orders).select('orders.price_total AS price_total', 'articles.price_cost AS price_cost', 'orders.quantity AS quantity').where("orders.created_at::date >= ? and orders.created_at::date <= ?", @from, @to)

    @earnings.each do |a| 
      a.quantity = 0 if a.quantity.nil?
      a.price_cost = 0 if a.price_cost.nil?
      a.price_total = 0 if a.price_total.nil?
      sum += a.price_total - (a.price_cost * a.quantity)
    end
    sum
  end
end

app/controllers/accounting_records_controller.rb
class AccountingRecordsController < ApplicationController

  require 'will_paginate'
  before_action :set_accounting_record, only: [:show, :edit, :update, :destroy]

  # GET /accounting_records
  # GET /accounting_records.json
  def index
    @accounting_records = AccountingRecord.journal
    @accounting_records = AccountingRecord.filters(params[:q]) if params[:q].present?
    @credit = AccountingRecord.credit(@accounting_records)
    @debit = AccountingRecord.debit(@accounting_records)
    @caja_total = @debit - @credit
    @accounting_records =  @accounting_records.paginate(page: params[:page], per_page:10)

    @earnings = AccountingRecord.earnings(params[:q]) if params[:q].present? 

    @earnings = AccountingRecord.earnings if (params[:q].nil?)

  
  end

  # GET /accounting_records/1
  # GET /accounting_records/1.json
  def show
  end

  # GET /accounting_records/new
  def new
    @accounting_record = AccountingRecord.new
  end

  # GET /accounting_records/1/edit
  def edit
  end

  # POST /accounting_records
  # POST /accounting_records.json
  def create
    @accounting_record = AccountingRecord.new(accounting_record_params)

    respond_to do |format|
      if @accounting_record.save
        format.html { redirect_to accounting_records_path, notice: 'Accounting record was successfully created.' }
        format.json { render :show, status: :created, location: @accounting_record }
      else
        format.html { render :new }
        format.json { render json: @accounting_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounting_records/1
  # PATCH/PUT /accounting_records/1.json
  def update
    respond_to do |format|
      if @accounting_record.update(accounting_record_params)
        format.html { redirect_to @accounting_record, notice: 'Accounting record was successfully updated.' }
        format.json { render :show, status: :ok, location: @accounting_record }
      else
        format.html { render :edit }
        format.json { render json: @accounting_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounting_records/1
  # DELETE /accounting_records/1.json
  def destroy
    @accounting_record.destroy
    respond_to do |format|
      format.html { redirect_to accounting_records_url, notice: 'Accounting record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounting_record
      @accounting_record = AccountingRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accounting_record_params
      params.require(:accounting_record).permit(:detail, :debit, :credit)
    end
end

app/helpers/accounting_records_helper.rb
module AccountingRecordsHelper
end

app/views/accounting_records/_filters_bar.html.erb
<%= form_for '', :method => :get  do |f| %>
  <div>
  <ul class="nav nav-list bordered">

    <li class="nav-header bordered">
    <a data-toggle="collapse" href="#create"><%= image_tag("calendar-icon.png", height: '32') %>Fecha</a>
    </li>
    <li id="create" class="collapse filter-options">
    <%= text_field_tag 'q[from]', (params[:q][:from] rescue ""), :class => "col-md-8", :data => { :value => (params[:q][:from] rescue "") } %>
    <%= text_field_tag 'q[to]', (params[:q][:to] rescue ""), :class => "col-md-8", :data => { :value => (params[:q][:to] rescue "") } %>
    </li>
  </ul>
  <div>
    <%= f.submit  "Filtrar", class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/accounting_records/_form.html.erb
<%= simple_form_for(@accounting_record) do |f| %>

  <div class="container"> 
  <div class="form-inputs">
    <div class="row-fluid">
      <%= f.error_notification %>
      <div class="col-md-5">
        <div class="field">
          <%=f.input :detail, label: "Detalle", input_html: {class: "form-control" }  %>
        </div>
        <div class="field">
          <%= f.input :credit, label: "Ingreso" , input_html: {class: "form-control" }, as: :string %><br>
        </div>
        <div class="field">
          <%= f.input :debit , label: "Egreso",  input_html: {class: "form-control" }, as: :string %><br>
        </div>
        <div class="actions">
          <%= f.submit "Guardar", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/accounting_records/edit.html.erb
<div class="col-md-12"> 
  <div class="form-group">
    <div class="col-md-2 sidebar">

    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <div class="col-md-12 customer">
<h1>Editar Registro</h1>
<%= render 'form' %>
</div>
</div>
</div>
</div>

app/views/accounting_records/index.html.erb
<div class="col-md-12"> 
  <div class="form-group">
    <div class="col-md-2 sidebar">

      <%= render :partial => 'filters_bar' %>

    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <div class="col-md-8 customer">

<h1>Caja Diaria</h1>
<%= will_paginate @accounting_records %>
<table class="table">
  <thead>
    <tr>
      <th>Detalle</th>
      <th>Ingreso</th>
      <th>Egreso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounting_records.each do |accounting_record| %>
      <tr>
        <td><%= link_to accounting_record.detail, edit_invoice_path(accounting_record.invoice_id)  %>  </td>
        <td><%= number_to_currency(accounting_record.credit) %></td>
        <td><%= number_to_currency(accounting_record.debit) %></td>
        <td><%= link_to 'Editar', edit_accounting_record_path(accounting_record) %></td>
        <td><%= link_to 'Eliminar', accounting_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
      <tr>
        <td></td>
        <td><%= number_to_currency(@credit) %></td>
        <td><%= number_to_currency(@debit) %></td>
      </tr>
  </tbody>
</table>

        <div>
          <h4>Total de Caja: <%= number_to_currency(@caja_total) %></h3>
          <h4>Total de Ganancia: <%= number_to_currency(@earnings) %></h3>
        </div>
<%= link_to 'Nuevo Registro', new_accounting_record_path %>
</div>


</div>
</div>
</div>

app/views/accounting_records/new.html.erb
<div class="col-md-12"> 
  <div class="form-group">
    <div class="col-md-2 sidebar">

    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <div class="col-md-12 customer">
        <h1>Nuevo  Registro</h1>
        <%= render 'form' %>

      </div>
    </div>
  </div>
</div>

app/views/accounting_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Detail:</strong>
  <%= @accounting_record.detail %>
</p>

<p>
  <strong>Debit:</strong>
  <%= @accounting_record.debit %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @accounting_record.credit %>
</p>

<%= link_to 'Edit', edit_accounting_record_path(@accounting_record) %> |
<%= link_to 'Back', accounting_records_path %>