config/routes.rb
Rails.application.routes.draw do

  scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do

    resources :accounting_records

    resources :categories
    resources :customers do 
      get 'find/:id' => 'customers#find', as: :store, :on =>  :collection
      resources :current_accounts
    end

    resources :invoice_stocks
    resources :stocks
    resources :brands
    resources :orders do
    end
    resources :invoices do
      get :autocomplete_customer_name, :on => :collection
    end
    resources :suppliers
    resources :articles

    devise_for :users
    resources :users

  end 

  authenticated :user do 
    root :to => 'articles#index'
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :articles

  def self.total 
    Category.joins(articles: :orders).order(:name).group(:category_id, 'categories.name').sum('orders.price_total')
  end


  def self.total_con_fecha(date) 
    Category.joins(articles: :orders).where('orders.created_at::date >= ? and orders.created_at::date <= ?', date[:from].to_date, date[:to].to_date ).order(:name).group(:category_id, 'categories.name').sum('orders.price_total')
    
  end




end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index

    @categories = Category.total
    @categories = Category.total_con_fecha(params[:q]) if params[:q].present?
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_filters_bar.html.erb
<%= form_for '', :method => :get  do |f| %>
  <div>
  <ul class="nav nav-list bordered">

    <li class="nav-header bordered">
    <a data-toggle="collapse" href="#create"><%= image_tag("calendar-icon.png", height: '32') %>Fecha</a>
    </li>
    <li id="create" class="collapse filter-options">
    <%= text_field_tag 'q[from]', (params[:q][:from] rescue ""), :class => "col-md-8", :data => { :value => (params[:q][:from] rescue "") } %>
    <%= text_field_tag 'q[to]', (params[:q][:to] rescue ""), :class => "col-md-8", :data => { :value => (params[:q][:to] rescue "") } %>
    </li>
  </ul>
  <div>
    <%= f.submit  "Filtrar", class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Menu de Navegacion</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <%= render :partial => 'filters_bar' %>
      </div>
    <br>
<div>
      <%= link_to 'Nuevo Articulo', new_article_path %>
</div>

    </div>
    <div class="col-sm-offset-2 col-md-9 col-md-offset-3">

      <div>
        <% if flash[:error] %>
          <li class="alert alert-error"><%= flash[:error]  %></li>
      <% end %>
        <% if notice %>
          <li class="alert alert-success"><%= notice  %></li>
      <% end %>
      </div>
<h1>Listado de Categorias</h1>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category[0][0] %></td>
        <td><%= category[0][1] %></td>
        <td><%= number_to_currency(category[1]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Categoria', new_category_path %>

    </div>
    </div>
    </div>

app/views/categories/new.html.erb
<h1>Nueva Categoria</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>